# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"!\n\x10\x41uthorizeRequest\x12\r\n\x05token\x18\x01 \x01(\t\"Q\n\x0f\x41uthorizeResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12#\n\x05\x65rror\x18\x02 \x01(\x0e\x32\x0f.auth.AuthErrorH\x00\x88\x01\x01\x42\x08\n\x06_error*3\n\tAuthError\x12\x11\n\rINVAILD_TOKEN\x10\x00\x12\x13\n\x0f\x41\x43\x43OUNT_BLOCKED\x10\x01\x32K\n\x0b\x41uthService\x12<\n\tAuthorize\x12\x16.auth.AuthorizeRequest\x1a\x15.auth.AuthorizeResult\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_AUTHERROR']._serialized_start=138
  _globals['_AUTHERROR']._serialized_end=189
  _globals['_AUTHORIZEREQUEST']._serialized_start=20
  _globals['_AUTHORIZEREQUEST']._serialized_end=53
  _globals['_AUTHORIZERESULT']._serialized_start=55
  _globals['_AUTHORIZERESULT']._serialized_end=136
  _globals['_AUTHSERVICE']._serialized_start=191
  _globals['_AUTHSERVICE']._serialized_end=266
# @@protoc_insertion_point(module_scope)
